title: scienlib
description: Scienlib is a scientific Python library that adds mathematical functions and adds other functions like physics, but also has cybersecurity and other functions
theme: jekyll-theme-cayman
author:
  name: Dylan Meca
  email: 

show_downloads: false
google_analytics: G-588R86TJDG
copyright: "Dylan Meca"
comments: false
show_excerpts: false
